EmployeesApp.Web/Controllers/CompaniesController.cs
using EmployeesApp.Application.Companies.Interfaces;
using EmployeesApp.Application.Employees.Interfaces;
using EmployeesApp.Domain.Entities;
using EmployeesApp.Web.Views.Companies;
using EmployeesApp.Web.Views.Employees;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeesApp.Web.Controllers;


[Route("company")]
public class CompaniesController : Controller
{

    private readonly ICompanyService _companyService;
    private readonly IEmployeeService _employeeService;

    public CompaniesController(ICompanyService companyService, IEmployeeService employeeService )
    {
        _companyService = companyService;
        _employeeService = employeeService;
    }





    [HttpGet("")]
    public  async Task <IActionResult> CompanyIndexAsync()
    {
        var company = (await _companyService.GetAllAsync());
        var viewModel = company.Select(c => new CompanyIndexVM
        {
            Id = c.Id,
            Name = c.Name,
            EmployeesCount = c.Employees.Count 
        }).ToList();
        return View(viewModel);


        }




    [HttpGet("create")]
    public IActionResult CompanyCreate()
    {
        return View(new CompanyCreateVM());
    }





    [HttpPost("create")]
    public async Task <IActionResult> CreateAsync(CompanyCreateVM vm)
    {

        if (ModelState.IsValid)
        {
            var company = new Company
            {

                Name = vm.Name
               
            };

             await _companyService.AddAsync(company);
            //_logger.LogInformation("New company created! Name: {Name}", company.Name);
            return RedirectToAction("CompanyIndex");
        }

        return View(vm);
    }



    
    [HttpGet("connect")]
    public async Task <IActionResult> ConnectEmployeeAsync()
    {
        var model = new ConnectEmployeeVM
        {
            Employees = (await _employeeService.GetAllAsync())
                .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Name })
                .ToList(),

            Companies = (await _companyService.GetAllAsync())
                .Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name })
                .ToList()
        };

        return View(model);
    }




    [HttpPost("connect")]
    public async Task <IActionResult> ConnectEmployeeAsync(ConnectEmployeeVM model)
    {

        if (model.SelectedEmployeeId.HasValue && model.SelectedCompanyId.HasValue)
        {
            await _employeeService.ConnectToCompanyAsync(model.SelectedEmployeeId.Value, model.SelectedCompanyId.Value);
            return RedirectToAction("CompanyIndex");
        }

        ModelState.AddModelError("", "Choose one employee and one company.");
        return View(model);



        }






    [HttpGet("get/{id}")]
    public async Task<IActionResult> GetCompanyAsync(int id)
    {
        var company = await _companyService.GetAsync(id);

        if (company == null)
            return NotFound();

        return Ok(company);





    }

    // Run this in browserDebugger : fetch('/delete/id', { method: 'POST' });


    [HttpPost("/delete/{id}")]
    public async Task<IActionResult> RemoveCompany(int id)
    {

        //var company = await _companyService.GetAsync(id);

        //    if (company == null)
        //    return NotFound();

        await _companyService.DeleteAsync(id);
        return RedirectToAction("CompanyIndex");





    }
















}





































//        // GET: CompaniesController/Details/5
//        public ActionResult Details(int id)
//        {
//            return View();
//        }

//        // GET: CompaniesController/Create
//        public ActionResult Create()
//        {
//            return View();
//        }

//        // POST: CompaniesController/Create
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Create(IFormCollection collection)
//        {
//            try
//            {
//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View();
//            }
//        }

//        // GET: CompaniesController/Edit/5
//        public ActionResult Edit(int id)
//        {
//            return View();
//        }

//        // POST: CompaniesController/Edit/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit(int id, IFormCollection collection)
//        {
//            try
//            {
//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View();
//            }
//        }

//        // GET: CompaniesController/Delete/5
//        public ActionResult Delete(int id)
//        {
//            return View();
//        }

//        // POST: CompaniesController/Delete/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Delete(int id, IFormCollection collection)
//        {
//            try
//            {
//                return RedirectToAction(nameof(Index));
//            }
//            catch
//            {
//                return View();
//            }
//        }
//    }
//}

EmployeesApp.Web/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using EmployeesApp.Web.Views.Home;
using Microsoft.Extensions.Logging;
using EmployeesApp.Application.Employees.Interfaces;
using EmployeesApp.Domain.Entities;
using Microsoft.Extensions.Logging.Abstractions;
using EmployeesApp.Web.Views.Employees;
using EmployeesApp.Application.Companies.Interfaces;

namespace EmployeesApp.Web.Controllers;

[Route("employee")]
public class EmployeesController : Controller
{
    private readonly IEmployeeService _employeeService;
    private readonly ILogger<EmployeesController> _logger;

    public EmployeesController(IEmployeeService employeeService, ILogger<EmployeesController>? logger = null) // Nu med filter och ILogger
    {
        _employeeService = employeeService;
        _logger = logger ?? NullLogger<EmployeesController>.Instance;
    }


    [HttpGet("")]
    public async Task <IActionResult> EmployeeIndexAsync()
    {

        var employees = (await _employeeService.GetAllAsync());
        var viewModels = employees.Select(e => new EmployeeIndexVM
        {
            Id = e.Id,
            Name = e.Name,
            Email = e.Email,
            Salary = e.Salary,
            CompanyName = e.Company?.Name ?? "" 

        }).ToList();
        _logger.LogInformation("Number of employees: {count}", viewModels.Count);

        return View(viewModels);



    }



    [HttpGet("create")] 
    public IActionResult EmployeeCreate()
    {

        return View(new EmployeeCreateVM());
    }








    [HttpPost("create")]
    public async Task <IActionResult> CreateAsync(EmployeeCreateVM vm)
    {

        if (ModelState.IsValid)
        {
            var employee = new Employee
            {

                Name = vm.Name,
                Email = vm.Email,
                Salary = vm.Salary
            };

           await _employeeService.AddAsync(employee);
            _logger.LogInformation("New employee created! Name: {Name}", employee.Name);
            return RedirectToAction("EmployeeIndex");
        }

        return View(vm);
    }







}

EmployeesApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - EmployeesApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark">


@*     <link rel="stylesheet" href="https://unpkg.com/@@picocss/pico@latest/css/pico.classless.min.css">             *@ @* vanliga classless *@
@*     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@picocss/pico@2/css/pico.fluid.classless.min.css"> *@ @* med fluid-classless *@
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@picocss/pico@2/css/pico.min.css">                  @* Vanliga/hela PICO *@
    

    <link rel="stylesheet" href="~/css/site.css" />


</head>

<body>

    <!-- the menu -->
    <nav class="centered-nav">
      @*   <ul>
            <li><strong>EmployeesApp</strong></li>
        </ul> *@
        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index"
                   class="@(ViewContext.RouteData.Values["controller"]?.ToString() == "Home" ? "active" : "")">
                    Home
                </a>
            </li>

            <li>
                <a asp-controller="Employees" asp-action="EmployeeIndex"
                   class="@(ViewContext.RouteData.Values["controller"]?.ToString() == "Employees" ? "active" : "")">
                    Employees
                </a>
            </li>


            <li>
                <a asp-controller="Companies" asp-action="CompanyIndex"
                   class="@(ViewContext.RouteData.Values["controller"]?.ToString() == "Companies" ? "active" : "")">
                    Companies
                </a>
            </li>




@*             <li><a asp-controller="Companies" asp-action="CompanyIndex">Companies</a></li>


 *@            @* <li><a asp-controller="Employees" asp-action="EmployeeCreate" role="button">Add Employee</a></li> *@
        </ul>
    </nav>

    <!-- the content -->
    <main class="wrapper">
        @RenderBody()
    </main>
    @RenderSection("Scripts", required: false)
</body>
</html>

    














@* ----------------from before-------------------
<body>


    <main>
        @RenderBody()
    </main>
    @RenderSection("Scripts", required: false)
</body>
</html>  *@